finnhub:
  api:
    key: "c0pait748v6rvej4h5ig"
reddit:
  user:
    username: Soggy-Eye6520
    password: muwcufVnH<y6TYQ
  api:
    app-id: 5nTptwCytJKtlQ
    app-secret: xkhr5E8UDhotk8ZFy5qCGSB2xcPQVw